CMS/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CMS.Models
{
    public class Comment
    {
        public Guid Id { get; set; }
        public string UserId { get; set; }
        public Guid PageId { get; set; }
        public Guid? ParentId { get; set; }
        public string Body { get; set; }
        public DateTime Posted { get; set; }
        
    }
}

CMS/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CMS.Data;
using CMS.Models;
using CMS.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CMS.Controllers
{
    public class CommentsController : Controller
    {
        private CMSContext _context;

        public CommentsController(CMSContext context)
        {
            _context = context;
        }

        public List<Comment> getComments()
        {
            return _context.Comments.ToList();
        }

        [HttpPost]
        public IActionResult getComments([FromBody]Guid pageId)
        {
            // all comments
            var allComments = _context.Comments.Where(c => c.PageId == pageId).ToList();
            ViewBag.Comments = allComments;
            //only top level comments
            return PartialView(allComments.Where(c => c.ParentId == null).ToList());
        }

        [HttpPost]
        public IActionResult newCommentForm([FromBody]Comment comment)
        {
            return PartialView(comment);
        }


        //[HttpPost]
        //public async Task<bool> Create([FromBody] Comment comment)
        //{

        //    _context.Add(comment);
        //    await _context.SaveChangesAsync();
        //    return true;


        //}
    }
}

CMS/Controllers/UserManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CMS.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CMS.Controllers
{
    public class UserManagerController : Controller
    {
        private UserManager<User> _userManager;

        public UserManagerController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> GetUserLists()
        {
            var userslist = _userManager.Users.ToList();

            List<User> userslist2 = new List<User>();

            foreach (var bob in userslist)
            {
                userslist2.Add(new User { Email = bob.Email });
            }


            return View(userslist);
            //return View(userslist2);
        }

        public async Task<IActionResult> BlockUserFromSite(string user)
        {
            User RemovedUser = await _userManager.FindByEmailAsync(user);

            await _userManager.RemoveFromRoleAsync(RemovedUser, "Admin");
            await _userManager.RemoveFromRoleAsync(RemovedUser, "Contributor");




            return View("../Home/Index");
        }

        public async Task<IActionResult> UpgradeToAdmin(string user)
        {
            User NewAdminUser = await _userManager.FindByEmailAsync(user);

            await _userManager.AddToRoleAsync(NewAdminUser, "Admin");

            return View("../Home/Index");
        }
    }
}

CMS/Views/Shared/ImageButton.cshtml
<!-- Button to Open the Modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
        Check Images
    </button>

    <!--TODO: Add handler for the image uploaded-->
    <!-- The Modal -->
    <div class="modal" id="myModal">

        <div class="modal-dialog modal-lg" style="max-height: 5000px;">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Images</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <div class="d-inline-flex flex-wrap" id="imageList">
                    </div>

                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <form id="imageUploadForm" asp-action="UploadImage" enctype="multipart/form-data">
                        <label>Upload Image</label>
                        <input type="file" name="image" id="inputFile" />
                        <input type="submit" value="upload" class="btn btn-outline-primary" />
                    </form>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>

                    <script>
                        $.post('/image/UploadImage', function (res) {
                            $('#imageList').html(res);
                            $('#imageList').find('img').click(function (e) {
                                $('#targetImage').attr("src", this.src);
                                $('#targetImageId').attr("value", this.id);
                            });
                        });


                        $('#imageUploadForm').submit(function (e) {
                            e.preventDefault();
                            var formData = new FormData();
                            formData.append("image", $('#inputFile')[0].files[0]);
                            $.ajax({
                                url: "/image/UploadImage",
                                type: "post",
                                data: formData,
                                processData: false,
                                contentType: false,
                                success: function (res) {
                                    $('#imageList').html(res);

                                }
                            });
                            $('#imageList').find('img').click(function (e) {
                                $('#targetImage').attr("src", this.src);
                            });
                        });

                    </script>
                </div>

            </div>
        </div>
    </div>

CMS/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@using CMS.Services
@inject IAuthorizationService Authorization
@{
    var canEdit = (await Authorization.AuthorizeAsync(User, MyIdentityDataService.BlogPolicy_Edit)).Succeeded;
    var canDelete = (await Authorization.AuthorizeAsync(User, MyIdentityDataService.BlogPolicy_Delete)).Succeeded;
    var canAdd = (await Authorization.AuthorizeAsync(User, MyIdentityDataService.BlogPolicy_Add)).Succeeded;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CMS</title>
    <link href="https://fonts.googleapis.com/css?family=Nunito|Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.js"></script>
    <link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.7.1/themes/base/jquery-ui.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>



    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div>
            <ul class="navbarUl">
                <a asp-area="" asp-controller="Home" asp-action="Index"><img src="~/img/logo2.png" height="50px" width="190px" id='logo' /></a>

                <li class="navbarLi"><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="navbarLi"><a asp-controller="Home" asp-action="ListofPages">List Of Pages</a></li>
                <li class="navbarLi"><a asp-controller="Home" asp-action="RequirementsPage">Requirements</a></li>
                @if (canAdd && canEdit)
                {
                    <li style="background-color:green" class="navbarLi"><a asp-area="" asp-controller="UserManager" asp-action="GetUserLists">User Manager</a></li>
                    <li class="navbarLi"><a asp-area="" asp-controller="Home" asp-action="BuildPage">Page Builder</a></li>
                }
                @if (SignInManager.IsSignedIn(User))
                {
                    <li class="navbarLi" style="float:right">
                        <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <button class="navbarButton" type="submit">Logout</button>
                        </form>
                    </li>
                    <li class="navbarLi" style="float:right">
                        <a asp-controller="Home" asp-action="Profile" title="Manage">Hello @User.Identity.Name!</a>
                    </li>

                }
                else
                {
                    <li class="navbarLi" style="float:right">
                        <a asp-area="Identity" asp-page="/Account/Register">Register</a>
                    </li>
                    <li class="navbarLi" style="float:right; background-color:#27b0c9">
                        <a asp-area="Identity" asp-page="/Account/Login">Login</a>
                    </li>
                }

            </ul>
        </div>
    </header>
    <div class="container">
        <main>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    
    </footer>


    @RenderSection("Scripts", required: false)
</body>
</html>

CMS/Views/Shared/_comments.cshtml
@model Guid
@{
//page id
}

<script src="~/lib/signalr/dist/browser/signalr.min.js"></script>
<script>
    function reloadComments() {
        $.ajax({
            url: "/Comments/getComments",
            type: "post",
            contentType: "application/json",
            data: JSON.stringify(@Html.Raw(Json.Serialize(Model))),
            success: function (data) {
                $('#commentIdnull').html(data);
            }
        });
    }
</script>
<div>
    <h4>Comments</h4>
    <h6>New Comment</h6>
    @Html.Partial("_newComment", new Comment { ParentId = null, PageId = Model })

    <hr />
    <div  id="commentIdnull">

    </div>

</div>
<script>
    reloadComments();
    var con = new signalR.HubConnectionBuilder().withUrl("/commentsHub").build();


    con.on("newComment", function (comment) {
        var parentid = 'commentId' + comment.parentId;
        var parent = document.getElementById(parentid);
        //debugger;
        parent.innerHTML +=`
        <div style="border-top: solid 1px; margin-left: 2em;">
        <p>User: ${comment.userId}</p>
        <p>${comment.body}</p>
        </div>`;
    });


    con.start();

</script>

CMS/Views/Shared/_newComment.cshtml
@model CMS.Models.Comment
@{
    Model.Id = Guid.NewGuid();

    var commentBtn = "button" + Model.Id;
    var newComment = "newComment" + Model.Id;
    var newCommentButtonFunction = "newCommentButton" + Model.Id.ToString().Replace("-", "") + "(event)";
}
<div id="@newComment">
    <script>
        function @newCommentButtonFunction{
                $.ajax({
                    url: "/Comments/newCommentForm",
                    type: "post",
                    contentType: "application/json",
                    data: JSON.stringify(@Html.Raw(Json.Serialize(Model))),
                    success: function (data) {
                        $('#@newComment').append(data);
                    }
                });
                $('#@commentBtn').addClass('d-none');
        }
    </script>
    <button id="@commentBtn" onclick="@newCommentButtonFunction" class="btn btn-primary">Comment</button>

</div>